//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faura.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;func_F009&quot;,
        ///    &quot;ID&quot;: &quot;2147479561&quot;,
        ///    &quot;ParameterCount&quot;: &quot;1&quot;,
        ///    &quot;Variables&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;unk1&quot;,
        ///        &quot;Value&quot;: &quot;0&quot;,
        ///        &quot;HasEnum&quot;: &quot;false&quot;,
        ///        &quot;EnumName&quot;: &quot;none&quot;
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;func_F010&quot;,
        ///    &quot;ID&quot;: &quot;2147479568&quot;,
        ///    &quot;ParameterCount&quot;: &quot;0&quot;,
        ///    &quot;Variables&quot;: []
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;SetPortrait&quot;,
        ///    &quot;ID&quot;: &quot;2147479583&quot;,
        ///    &quot;ParameterCount&quot;: &quot;2&quot;,
        ///    &quot;Variables&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;portraitSlot&quot;,
        ///        &quot;V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string metafalica {
            get {
                return ResourceManager.GetString("metafalica", resourceCulture);
            }
        }
    }
}
